name: xeus-octave
channels:
  - conda-forge
dependencies:
  - xeus-octave ==0.1.0
  # For Plotly graphical toolkit
  - plotly
  # Runtime dependency for Octave ``symbolic`` package.
  - sympy
  - pip
  - pip:
    - nbgitpuller
